### ISSUE TITLE
SetColor and GetColor Issues

### ISSUE THREAD

**Issue by LarsWerkman** [LarsWerkman/HoloColorPicker#55]
Dear users of HoloColorPicker,

I am aware of the issue, but due to school and work
I havent had much time to resolve it.
It will try to work it out as soon as possible!!

Thanks
Lars

**Comment by samskiter** [comment]
could you elaborate?

**Comment by Cliff2103** [comment]
I fixed the colorToAngle method can I push this?

**Comment by LarsWerkman** [comment]
@Cliff2103 Yes you always make a pull request!

**Comment by Cliff2103** [comment]
I created a pull request for this bug

**Comment by Tr1N3o** [comment]
Any fix on that issue yet?

**Comment by Cliff2103** [comment]
I fixed this in PR #77, but it’s still not accepted.

**Comment by LarsWerkman** [comment]
I'm sorry this took way to long for it to get fixed! but I accepted the pull request of @Cliff2103 #77

**Comment by cjapito** [comment]
Yea
