### ISSUE TITLE
XML Attributes for Bars are not accessible

### ISSUE THREAD

**Issue by Mariuxtheone** [LarsWerkman/HoloColorPicker#58]
Hello,

looks like the following atributes can't be accessed from XML even with namespace change.

         <attr name="bar_length" format="dimension" />
         <attr name="bar_pointer_radius" format="dimension" />
         <attr name="bar_pointer_halo_radius" format="dimension" />
         <attr name="bar_orientation_horizontal" format="boolean" />

The Wheel attributes are accessible.

I'm using the maven repository.

Thanks!

**Comment by LarsWerkman** [comment]
Sorry for the late response but its fixed in the current version, (Please reopen if it still occurs with you)
