### ISSUE TITLE
maven update request

### ISSUE THREAD

**Issue by Suxsem** [LarsWerkman/HoloColorPicker#64]
Hi. I think you should update the maven repo to reflect latest fixes

**Comment by tonyr59h** [comment]
:+1: for this. @LarsWerkman if you don't mind giving me group permissions I'd be happy to update it.

**Comment by LarsWerkman** [comment]
Hi @Suxsem I will try to get this done as soon as possible (I am sorry it slipped my mind, I haven been really busy lately)

**Comment by Suxsem** [comment]
Thanks :)

**Comment by m0w1337** [comment]
Could this be the reason, why I'm still having the vertical bar orientation problem on orientation change? Or do I have to look elswere for that problem?

**Comment by Suxsem** [comment]
@m0w1337 sure
