### ISSUE TITLE
value = -1?

### ISSUE THREAD

**Issue by Wolke** [LarsWerkman/HoloColorPicker#65]
picker.setOnColorChangedListener(new ColorPicker.OnColorChangedListener() {
            @Override
            public void onColorChanged(int i) {
                i <==sometimes will give -1;
            }
        });

---

**Comment by robodoggy** [comment]
@Wolke Can you provided a larger code sample (maybe a [Gist](https://gist.github.com/)), that will reproduce the bug?

**Comment by robodoggy** [comment]
Looking at the [Android Color documentation](http://developer.android.com/reference/android/graphics/Color.html), you should get a color of -1 to represent white. Are you getting this value at some other time, or is this actually intended behavior?

**Comment by Shnkc** [comment]
A color whose alpha value is bigger than 80 will be represented with a negative integer number since left-most bit represents sign of the an integer value. Therefore, it is a normal behavior.
