### ISSUE TITLE
Color selection to string

### ISSUE THREAD

**Issue by power7714** [LarsWerkman/HoloColorPicker#68]
Not really an issue. I need to be able to send the selected color as a string to a database. Is it possible to convert the selection to a string? If it is, how would I go about doing that? I'm very new to this library so any help in the right direction would be great. Thank you.

**Comment by robodoggy** [comment]
Have you looked at the [Android Color](http://developer.android.com/reference/android/graphics/Color.html) documentation? The color ints that HoloColorPicker creates is compliant with that class, and you can use that class to break a color into ARGB, HSVA or HSBA.

**Comment by power7714** [comment]
ok. will do. Quick question though, does HoloColorPicker create the int in a hex format that is compatible with web/css color codes?

**Comment by theBlbDan** [comment]
Documentations says:

```javadoc
int com.larswerkman.holocolorpicker.ColorPicker.getColor()
Get the currently selected color.
Returns:
The ARGB value of the currently selected color.
```

"int in a hex format" does not compute.  An int is an int.  If you aren't familiar with ARGB or HSLA, you have some homework to do.


But, to be courteous, no.  You need to use the [Android Color] (http://developer.android.com/reference/android/graphics/Color.html) class to help you get there.
```java
	int color = picker.getColor();
	long highlight_id = 0;
	String alpha = String.format("%02x", Color.alpha(color)),
				red = String.format("%02x", Color.red(color)),
				green = String.format("%02x", Color.green(color)),
				blue = String.format("%02x", Color.blue(color));
```
Now you have four strings that look like four hex values that resemble the ARGB.  You seem to be stuck in the mindset that CSS colors are always #AARRGGBB.  https://developer.mozilla.org/en-US/docs/Web/CSS/color_value.

enjoy

**Comment by devgutt** [comment]
I'm using this function
`String.format("#%06X", 0x00FFFFFF & color);`
