### ISSUE TITLE
Will HoloColorPicker design yield less possible color choice than a solid full circle?

### ISSUE THREAD

**Issue by yccheok** [LarsWerkman/HoloColorPicker#94]
Hi, I love `HoloColorPicker` design. It is really beautiful.

However, I was wondering, will `HoloColorPicker` yield less possible color choice than a solid full circle, as below?

<img width="133" alt="2019-03-13 23_13_49-palette png - paint net 4 0 21" src="https://user-images.githubusercontent.com/308276/54290335-b8b1d400-45e5-11e9-9862-5e9f965d6e17.png">

**Comment by sikaiser** [comment]
No, it should be the same. The system HoloColorPicker uses is HSV (hue, saturation, value). The circle represents hue, and then you need two bars for saturation and value respectively. With these three dimensions you can basically represent any color (ignoring some technical limitations that don't affect user experience).

The solid full circle in your picture just maps these dimensions differently, but it does not represent more colors.

**Comment by yccheok** [comment]
Thanks for the clarification. We understand it now.
